
# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# PureChat version string
# - string
version: "1.4.10-6"

# Set default factions plugin for PureChat
# - FactionsPro / null
default-factions-plugin: FactionsPro

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {display_name}, {msg}, {fac_name}, {fac_rank}, {prefix}, {suffix}, {world}
groups:
  Guest:
    chat: '&7{display_name} : &f{msg}'
    nametag: '&7[Guest] &f{display_name}'
    worlds: []
  Builder:
    chat: '&b[Bui] &7{display_name} : &f{msg}'
    nametag: '&b[B] &f{display_name}'
    worlds: []
  Moderator:
    chat: '&a[Mod] &7{display_name} : &f{msg}'
    nametag: '&a[M] &f{display_name}'
    worlds: []
  Admin:
    chat: '&6[Adm] &7{display_name} : &f{msg}'
    nametag: '&6[A] &f{display_name}'
    worlds: []
  Owner:
    chat: '&e[Own] &7{display_name} : &f{msg}'
    nametag: '&6[O] &f{display_name}'
    worlds: []
...
