---
Prevent-Pearling-In-Small-Areas: false
Prevent-Place-Block-Glitching: true
Prevent-Break-Block-Glitching: true
Prevent-Open-Door-Glitching: true
Prevent-Command-Glitching: true
CancelPearl-Message: §7[§bAntiGlitch§7] §cPearl Cancelled due to suffocation!
CancelBlockPlace-Message: false
CancelBlockBreak-Message: false
CancelOpenDoor-Message: false
CancelCommand-Message: §7[§bAntiGlitch§7] §cCommand Cancelled due to glitch detected!
...
