---
# InformationUI or InfoUI by Hytlenz (Lentou)
# for image-type: 0 is for default texture path from MCPE like "textures/ui/cancel"
#.                1 is for url from internet or source like "http://pocketpinas.cf/icon-pcp.png"
# Supported § for color

wikipedia:
  title: "§l§cPMnS"
  return: "§l< Back"
  content:
    - "§7Greetings, §a{player}"
    - ""
    - "§7Welcome to Information Centre"
    - ""
    - "§7Here you can read all"
    - "§7Informations regarding on this server"

wiki:
  about:
    button: "About PMnS"
    imgtype: 1
    imgpath: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/313/closed-book_1f4d5.png"
    title: "About Us"
    content:
      - "§l§bHistory:§r"
      - "PMnS is built as a minigames and factions server founded by WetzkieGamer, a popular Filipino Minecraft Youtuber"
      - "and he started creating content before, and with help with other Youtubers, Builders, and Developers, PMnS was a beautiful place to play"
      - "and as times goes by, PMnS has suffered, and thus Wetzkie decided to give the server ownership, and management to princepines"
      - "and we have tried to maintain, the later renamed the server as ThePMnS Network, but failed and decided to backup its server files, and close down the network."
      - "now after hiatus, This December 2021 PMnS was relaunch again, and trying to revive its old gamemodes, improve this server and make this server again a beautiful place to play with friends."
      - ""
      - "In admist of pandemic, PMnS will never stop to provide players a games that they would be enjoy to play, community driven decisions, and satisfying to play"
      - ""
      - "§l§6A Message from Owner:§r"
      - "Every moment in our lives is important, our Friends, Family, and everyone else,"
      - "I remember my cousin that have died recently, you know she cares about me, my future, and we have bonded together but a little time,"
      - "she died in the age of 31, and i was shocked because, lives can be that too short, and i always remember to myself that, our lives is temporary,"
      - "and we should value it everytime, even a little value, because life is temporary."
      - ""
      - "Take care always,"
      - "Lyco Tatierra (aka princpines)"
      - "§oOwner and Developer of PMnS§r"
  games:
    button: "Games"
    imgtype: 1
    imgpath: "https://emojipedia-us.s3.amazonaws.com/source/skype/289/crossed-swords_2694-fe0f.png"
    title: "Games"
    content:
      - "§l§6Pot§fPvP§r"
      - "Experience PotPVP like never before with Classic PMnS Map with obstacles, Community-voted PotPVP Items, and a CPS Limiter to make the play more fair and fun! also this equipped with Advance AntiGlitch and AntiAura."
      - ""
      - "§l§aSurvival Mode§r"
      - "Play Survival Mode, make friends, make war, and make memories as a team! Unleash your raiding skills, tactics, and lead the faction! Survival Mode is equipped with plugins that control the fairness of the Gamemode such as CPS Limiter, Advance AntiGlitch, AntiAura and more."
  events:
    button: "Events"
    imgtype: 1
    imgpath: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/joypixels/291/sparkles_2728.png"
    title: "Events"
    content:
      - "We have built an inhouse Auditorium to host various Events, Everyone can book and host the events within the server, and have fun playing @ PMnS"
      - ""
      - "Visit https://pmns.princepines.digital/"
      - "page2.php to book events"
  opensource:
    button: "Open Source"
    imgtype: 1
    imgpath: "https://cdn-icons-png.flaticon.com/512/888/888868.png"
    title: "Open Source"
    content:
      - "This Server is using an Open Source Server Software (PocketMine-MP), visit here -> github.com/pmmp/PocketMine-MP"
      - ""
      - "Plugins and Texture Packs used are available as Open Source, available at our Github Organization"
      - "github.com/PinakaMalupetnaServer"
      - ""
      - "Read about §lPMnS as Open Source§r"
      - "§b<Article not available yet>"
# You can add more forms just follow the format.
...
